### ISSUE TITLE
Make list of available resources visible

### ISSUE THREAD

**Issue by skodapetr** [funpdbe-consortium/funpdbe-client#7]
In spite of the readme the parameter ```--resource``` is mandatory.
In the readme is seems as it is not. It's also not easy to find out which values can this parameter takes. 
Taking names from https://www.ebi.ac.uk/pdbe/funpdbe/deposition/ is not working.

It seems that possible values are hardcoded in [constant.py](https://github.com/funpdbe-consortium/funpdbe-client/blob/master/funpdbe_client/constants.py) file. This is not obvious to the user. 

It would be great to provide a way how to list them, or mention this fact explicitly in the readme file.

**Comment by mvaradi** [comment]
This is intentional. A FunPDBe depositor need only know the resource name they are depositing to - this name actually comes from the FunPDBe account where every depositor has to register and apply for permission. The client is accessing the deposition API, not a production API - it is not intended for retrieving data from other resources than your own, and even for you own it is only as a checking tool to see if an entry has been successfully deposited.
